### ISSUE TITLE
why sfs contained decimals?

### ISSUE THREAD

**Issue by liuyanhu** [isaacovercast/easySFS#21]
I used easySFS to convert whole-genome sequencing vcf to SFS.  
There are  decimals in SFS (Fastsimcoal2 format) and the sfs values is small (further less then SNPs number).
How is it happen?
Wish your reply.
Thanks
Best

**Comment by isaacovercast** [comment]
Hello,
When posting an issue it typically helps to have more specific information about your question, for example it would help to the sfs that you're talking about. Overall the sfs can contain fractional values because the projection method essentially averages over snp frequencies to "fill in" missing data. It's also possible to construct an sfs with proportional bin frequencies, in which case all the bins will be fractional, and will sum to 1.

**Comment by isaacovercast** [comment]
Hope that helps!
