### ISSUE TITLE
No module named tridiag

### ISSUE THREAD

**Issue by PierreNois** [isaacovercast/easySFS#25]
Hello,

I install dadi and matplotlib module as you recommended it but I still have an error message when I run the easySFS script : "No module named tridiag". Do you know what can I change ?

Thank you !

Pierre

**Comment by isaacovercast** [comment]
Hello Pierre,

Looks like some things have changed since the last time I updated the docs. dadi is now in conda which makes things much easier. It also supports python3, which is great. I have updated the install instructions on the [README.md](https://github.com/isaacovercast/easySFS/blob/master/README.md) file.

Probably best to create a new conda env and just redo the install as it is now documented, rather than fiddling with a broken install. I tested the new directions just now and it works flawlessly. Give it a try and let me know how it goes.

-isaac
