### ISSUE TITLE
Monomorphic sites

### ISSUE THREAD

**Issue by laura1hagemann2** [isaacovercast/easySFS#48]
Dear Isaac, I used Freebayes v1.2.0 to create a vcf file and want to use easySFS and after epos.  The epos format needs to be r [tab] the number of polymorphic genomic sites with r copies of the derived allele. As I understand the dadi output the numbers in the first line are   the number of polymorphic genomic sites with r copies of the derived allele, starting with r=0. Is this correct? I am bit confused beacause my SFS starts like this: 0.2870 4.0469 22.4985 and this can hardly be true. I would really appreciate your help figuring out what is going wrong. Thank you very much Laura

**Comment by isaacovercast** [comment]
If the reference is the outgroup then you have all the information you need, since all you need to know is (presumed) ancestral state. Probably going with alignment length is going to give a more reasonable view of the data to epos.

As for r=1, Yes, this does seem small, and yes this could be a result of overly-stringent filtering. r=1 is the 'singletons' bin, and this is the bin that is most likely to get thrown out along with the 'bathwater' during qc.

Good luck!

**Comment by isaacovercast** [comment]
This isn't really a 'bug' with easySFS, so i'm going to close the issue, but feel free to email me directly if you have questions.
