### ISSUE TITLE
number of sites in datadict vs. folded sfs

### ISSUE THREAD

**Issue by tida-one** [isaacovercast/easySFS#57]
Hello Isaac,
thank you for this great tool. 
I have some difficulties to understand why the number of lines in my datadict fits exactly the number of SNPs, while this is not the case when I sum all the bin from the obtained folded SFS file.
For instance I have >33,000,000 lines in the datadict while the sum of the bins in the related SFS file is "only" 22,000,000.

Is the difference due to the projection?
How can I know which markers are filtered between the dict and the SFS?
Thank you

**Comment by isaacovercast** [comment]
Hello,

You are right that the number of SNPs in the sfs is smaller than the number of SNPs in the datadict because of the projection. Different projection values will remove different numbers of snps, this is part of the logic of the `--preview` command.  It's well explained on the [dadi faq](https://dadi.readthedocs.io/en/latest/user-guide/frequently-asked-questions/).

There is really no easy way to know which snps are excluded for a given projection value.

Glad you like easySFS, tell your friends! Hope that helps!

**Comment by tida-one** [comment]
Thank you Isaac for your reply and for the link.

My question came from the fact that I compared SFS obtained from easy SFS with "hard called" sites vs SFS obtained from realSFS after ANGSD with the same site list (i.e. the >33,000,000 sites). 

The SFS from realSFS after ANGSD is made using all sites (>33,000,000) while the one from easySFS is made with less sites (see my first post).

EASY-SFS=
10928375 3422751 1988802 1374622 1048935 801607 699045 632678 587183 570960 354287 0 0 0 0 0 0 0 0 0 0

REALSFS=
18830368.737755 3089188.261327 2374765.302058 1908451.712163 1556310.203886 1228082.40854 1128748.977158 1034160.385977 978797.157933 928567.886094 791569.967117 0 0 0 0 0 0 0 0 0 0

I may be wrong but the two folded SFSs are quite different (lack of singleton in the SFS from realSFS)  
1) I do not understand why there is such a difference 
2) which one should be considered as the "true" one?
3) I expect this to be a problem leading to different results in following analyses, right?

This may be a bit out of EASY SFS topic but if you have any idea.

Thank you

**Comment by isaacovercast** [comment]
1. There is a difference between the sfs because the methods are doing
different things. I do not know how angsd works so I can't say much about
it. easysfs has to remove sites that don't have sufficient sample coverage
for a given projection value, which is why it retains fewer sites.

2. I don't think one or the other is really more true, they are just
different sfs with different biases that generated them.

3. I think this is an open question. I do see that realSFS seems to have
fewer singletons which seems odd and also which seems like it would change
downstream analysis results. This would be something to potentially
experiment with using simulations.

Hope that helps,
-isaac

**Comment by tida-one** [comment]
Thank you for the time dedicated to this "off topic" question!
