### ISSUE TITLE
how to interpret folded sfs-vector?

### ISSUE THREAD

**Issue by mennodejong1986** [isaacovercast/easySFS#60]
I have a question regarding the interpretation of the folded sfs vector. 
Other people have asked similar questions, but despite your helpful replies I still do not fully understand how to interpret the 0's and 1's.

I give here a simplified example.
Say we have a dataset of 10 individuals, projected down to 6 individuals (i.e., --proj==6).
Based on the outcome for one of my datasets, the folded sfs-vector outputted by easysfs might look something like this:

1000 100 95 90 0 0 0 1 0 0 1 1 1

If ignoring the first value (number of monomorphic sites), we get:

100 95 90 0 0 0 1 0 0 1 1 1

When answering a previous question, you wrote: 'The zeros and ones are a bitmask to indicate which bins should be considered as data. In a folded sfs the row will contain 0s and 1s in roughly equal proportion, as a result of the folding procedure.'

From this, I understood that only the first 3 and the last 3 bins should be considered (but also one of the middle bins?). I figured that because it is a folded sfs, this means in practice: the first 3 bins only (i.e., the values 100, 95 and 90). 
However, given that I specified to project down to 6 diploid individuals, I expected to find a folded sfs-vector of 6 bins, not 3 bins.  

Could you explain how I should interpret the sfs-vector instead?
Thanks in advance for your help!

**Comment by isaacovercast** [comment]
Hello,
Is this a manufactured example or did you generate this example with easySFS? Here's an example using the simulated data from the easySFS repository:
```
./easySFS.py -i example_files/sims.vcf -p example_files/sims_pops.txt --proj 6,6,6 -f
```
Which generates this file (in the dadi directory) for pop1:
```
7 folded "pop1"
722.8214285714286 168.6428571428572 94.53571428571425 14 0 0 0
1 0 0 0 1 1 1
```

Here the '1' in the second row indicates the value is masked ([standard dadi format](https://dadi.readthedocs.io/en/latest/user-guide/importing-data/)), so the first bin (monomorphic) is masked and the last 3 bins are masked because the sfs is folded.

Recall that when specifying `--proj` the value considered is _always_ the number of haploid samples to project down to, perhaps that was causing some of the confusion? Let me know if that helps.

**Comment by mennodejong1986** [comment]
Thanks for your quick reply. This explains it all! 
I indeed wrongly assumed that the projection value referred to diploid individuals. Furthermore, in the (indeed manufactured) example the binmasking values were pasted behind the sfs-vector.
